# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f51e1f2773248718cea79ca9351571dfef7da29903af9f1b6b94148b246b4ee85cf006a4daff1e20817a2192f94482819a9c3eb6b0e3fdf13032dd4a62ad097d

test:
  secret_key_base: bad36df208a69370b0350519a4d2b4c93bd2490be056f6b0dc350fd19220f20dd9678684b8501ec5e1280aa295aec81f222bb8a1b055380ac06c3da734cc8779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
